
[cursor.style]
shape = "Beam"

[font]
size = 10.0

[font.normal]
family = "JetbrainsMonoNL Nerd Font"
# style = "Bold"

[window]
opacity = 1

[window.padding]
x = 10
y = 10

[general]
import = ["/home/mili/.config/alacritty/active_theme.toml"]
